### ISSUE TITLE
[Android][Animation] Interpolated translateY value causes android view to jump. 

### ISSUE THREAD

**Issue by mmamoyco** [react/react-native#21801]
- [+] Review the documentation: https://facebook.github.io/react-native
  - [+] Search for existing issues: https://github.com/facebook/react-native/issues
  - [+] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 862.68 MB / 16.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v10.9.0/bin/yarn
      npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: ^0.57.3 => 0.57.3
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
 I'm trying to implement collapsible header using React Native Animated API. using event method i get AnimatedHeaderValue and interpolate it into translateY value.
This value i apply to container of my listView (so listView moves vertically).
IOS animation works perfectly, but Android animation jumping and lagging when i scroll. I tried to inscrease scroll value and Android animation became more smooth.

This is scrollView container that passes onScroll to scrollView (listView)

`
 <ScCompanyNewsFeedList optimizeHeight 
                getRef={scrollView => {
                  console.log("SCROLL VIEW", scrollView)
                  this._scrollView = scrollView;
                }}  
                scrollEventThrottle = { 2 }
                onScroll={Animated.event(
                    [{ nativeEvent: { contentOffset: { y: this.AnimatedHeaderValue }}}],
                )} 
                companyId={this.props.companyId}/>
              }
`

this is base container that contains tabs and my scrollView. It's moving when scroll.

`
  <Animated.View style={[{flex: 1}, {transform: [{translateY: headerHeight}]}]}>
...
</Animated.View>
`

Interpolation

`
   const animationRange = this.AnimatedHeaderValue.interpolate({
      inputRange: [0, scrollRange],
      outputRange: [0, 1],
      extrapolate: "clamp"
    });
    const headerHeight2 = animationRange.interpolate({
      inputRange: [0, 1],
      outputRange: [0, -200]
    });
`

**Comment by godofmadness** [comment]
The issue still exists on rn 0.57

**Comment by darylalexjohnson** [comment]
@godofmadness You ever resolve this issue?

**Comment by godofmadness** [comment]
@darylalexjohnson nope, issue still exist.

**Comment by lindesvard** [comment]
Having similar issues..

**Comment by d2dindustries** [comment]
I am also having this issue. Any resolution in sight?

**Comment by Ghuller** [comment]
I'm also having this issue using RN 0.57.8.

It looks like it only happens when you have a decreasing outputRange, like [100, 0], or in OP's case, [0, -200]. It also happens with animated margins and paddings.

**Comment by kelset** [comment]
Does this still happen on 0.58?

**Comment by Ghuller** [comment]
@kelset Yes. Here is a example tested on RN 58.1:

```
import React, { Component } from "react";
import { Animated, View, StyleSheet } from "react-native";

export default class Example extends Component {
  state = {
    scrollY: new Animated.Value(0)
  };

  render() {
    const marginTopAnimated = this.state.scrollY.interpolate({
      inputRange: [0, 100],
      outputRange: [100, 0],
      extrapolate: "clamp"
    });

    return (
      <View style={{ flex: 1, backgroundColor: "skyblue" }}>
        <Animated.ScrollView
          style={[
            styles.scrollView,
            {
              transform: [{ translateY: marginTopAnimated }]
            }
          ]}
          scrollEventThrottle={16}
          onScroll={Animated.event(
            [
              {
                nativeEvent: { contentOffset: { y: this.state.scrollY } }
              }
            ],
            { useNativeDriver: true }
          )}
        >
          <View style={{ height: 1000 }} />
        </Animated.ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: "#FFF",
    borderTopRightRadius: 28,
    borderTopLeftRadius: 28
  }
});
```

Just create a new project with react-native init and paste it on App.js. Here is a gif of the result:

![example-animation](https://user-images.githubusercontent.com/29331129/51825378-ccbaa400-22cb-11e9-8297-c13fa885cfa1.gif)

**Comment by benevbright** [comment]
Hi, I'm maintaining `react-navigation-collapsible`. 
This issue is critical for this module and I tried many things for a workaround but no luck.

**Comment by benevbright** [comment]
https://github.com/facebook/react-native/issues/15445
It has not been fixed for a long time though.

**Comment by kelset** [comment]
Are there any PRs open to try and fix this? Or commits already on master?

**Comment by davidkalosi** [comment]
any news on this issue, it's a pretty annoying and visually nasty bug 

thx

**Comment by httol** [comment]
I think this is a serious issue, but nobody has any solution,hahah

**Comment by d2dindustries** [comment]
Is anyone looking into this?

**Comment by stockrel** [comment]
+1

**Comment by ddedic** [comment]
+1

**Comment by coder4affine** [comment]
+1

**Comment by davidkalosi** [comment]
bump again, can we get at least a milestone / time frame when this will be addressed?

**Comment by Albert0405** [comment]
1 Eternity Later...............

This bug still exists on v0.59

**Comment by kelset** [comment]
> can we get at least a milestone / time frame when this will be addressed?

AFAIK this issue is not in the roadmap - the best idea would be for someone actually concerned with this issue to investigate it more and submit a PR. A lot of work has been done to improve the PR to master timing so that would be the best way.

We are currently re-thinking how to approach issues so maybe in the next few days someone will be able to pick this up - but, again, since you are experiencing the issue you may have more time to dedicate to it.

**Comment by Albert0405** [comment]
@benevbright Hello, I started using your react-navigation-collapsible unfortunately the bug on android where the header started to jump when scrolling slowly. I made a hack way to avoid the "jumping bug" but i dont how to implement it on your library but i hope it helps

https://snack.expo.io/r1hwBv0wV - Here's the one with "Jumping Bug"
https://snack.expo.io/Hk34BPCDN - Here's the one without the bug

I just add the following style
```
position: 'absolute',
zIndex: 999,
top: 0
```

i dont know but i think the `position: 'absolute'` removes the bug

**Comment by brunohkbx** [comment]
Any update on this?

**Comment by belgamo** [comment]
+1

**Comment by Albert0405** [comment]
They dont give a sh*t anymore to this bug. This is the reason why RN devs are going flutter.

**Comment by brunohkbx** [comment]
Hey @kelset, how much time until Mid-Priority issues get fixed?

**Comment by kelset** [comment]
I don't know, as I mentioned previously:

> AFAIK this issue is not in the roadmap - the best idea would be for someone actually concerned with this issue to investigate it more and submit a PR. A lot of work has been done to improve the PR to master timing so that would be the best way.

Also, we are trying to focus on getting an RC for 0.60 out this week, so 🤞, maybe it's fixed on master?

**Comment by wuchangming** [comment]
@AaaChiuuu ， I think it‘s not a good workaround. Demo without the bug just because header layout Animation do not affect scrollview.  
https://snack.expo.io/@wuchangming/bad-donut-x

**Comment by alishamae** [comment]
Unsubscribe

**Comment by HarshitMadhav** [comment]
@kelset I am using 0.59.8 version. This issue still persists. Is it fixed in 0.60?

**Comment by HarshitMadhav** [comment]
In react-native version 0.64.0 this issue has been resolved as this commit has been merged to the master https://github.com/facebook/react-native/commit/f954f3d9b674b13977f722bc3b8dc6c1b99fe6c7

**Comment by wenkangzhou** [comment]
Has any idea for below 0.60.4?

**Comment by Albert0405** [comment]
@HarshitMadhav react-native version 0.64.0? you mean 0.60.4....?

The bug still persist on RN v0.60.4

**Comment by HarshitMadhav** [comment]
@Albert0405 read out this comment https://github.com/react-native-community/releases/issues/130#issuecomment-519191161

**Comment by HarshitMadhav** [comment]
I referenced this issue to the react-native latest discussions and got to know that this has been resolved in react-native version 0.64.4 refer here https://github.com/react-native-community/releases/issues/130#issuecomment-519191161

**Comment by brunohkbx** [comment]
cc @benevbright

**Comment by benevbright** [comment]
I just tried the latest RN, 0.60.5. But the issue is still happening. 

Feel free to try this example. 
https://github.com/benevbright/react-navigation-collapsible/tree/master/example

#### GIF
![Aug-18-2019 6-19-48 PM](https://user-images.githubusercontent.com/916690/63230386-1fc65b00-c20c-11e9-8651-7fd0bc9405bc.gif)

**Comment by sunnylqm** [comment]
@HarshitMadhav  That commit had been merged since 0.47.
![image](https://user-images.githubusercontent.com/615282/63254439-594ba480-c2a6-11e9-9d7d-89a5e5e35532.png)
![image](https://user-images.githubusercontent.com/615282/63254466-62d50c80-c2a6-11e9-88c9-67951d45a4bf.png)

Why do you think that old commit is related to this issue?

**Comment by benevbright** [comment]
Ok, I guess we totally misunderstood. 
Thanks! @sunnylqm

**Comment by HarshitMadhav** [comment]
@sunnylqm Yeah, I think we totally misunderstood these commits. Thanks!

**Comment by SathishSaminathan** [comment]
Anyone has solution?

**Comment by nidorx** [comment]
@benevbright, I'm implementing an application to document a component library I own.

In the app, the header is animated and I went through the same problem described here.

To solve the problem, I made the following adjustments to my component.

1 . Additional content is passed through the page to NavigationHeader via props
2. NavigationHeader looks at content height and tells page about new size
3. The page, which has ScrollView (or SectionList and etc), renders an empty element with this height received (a padding at the top), so the page does not use "transform: [{translateY: translateY} animation ] "(which is the source of the problem)
4. On the page, another aesthetic adjustment was to remove the vertical scroll bars (showsVerticalScrollIndicator = {false}). In the future I intend to create a virtual scroll bar, just to allow the visual response to the user about the screen position, discounting the height of the empty component.

The implementation files (and most important lines) are:

* https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/NavigationHeader.tsx#L264-L288
* https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/NavigationHeader.tsx#L232-L235
* https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/GradientHeader.tsx#L29-L54
* https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/GradientHeader.tsx#L69-L70

Below are two videos with the result, (you can also run the application https://github.com/nidorx/rn-components-ui/tree/master/example and see the result [still under development] for yourself)

AnimationHeader - https://youtu.be/IyThm01At1g

Page padding top -  https://youtu.be/kNwCq6xYEHQ


![ezgif com-optimize](https://user-images.githubusercontent.com/675430/63904107-3a57bb80-c9e6-11e9-8c5f-453141560b7a.gif)

**Comment by benevbright** [comment]
@nidorx 
Hi, Thanks for the comment. 

But your solution is off the topic. 
Because you don't use `translateY` on `ScrollView` but gave top margin and translate "Header".

This bug is about using `translateY` on `ScrollView`.

**Comment by nidorx** [comment]
> @nidorx
> Hi, Thanks for the comment.
> Nice workaround.
> 
> But your solution is off the topic.
> Because you don't use `translateY` on `ScrollView` but gave top margin and translate "Header".
> 
> This bug is about using `translateY` on `ScrollView`.


*...so the page does not use "transform: [{translateY: translateY} animation ] "(which is the source of the problem)*

It is not offtopic in reality, in the previous implementation I suffered from the same problem described, to solve the problem, I stopped using translateY and started using a padding at the top.

**Comment by benevbright** [comment]
@nidorx 
Yes, I understood. 
But what I’m saying is that it’s a workaround. 
And here we want this bug will be fixed so we can use translateY on ScrollView.

**Comment by FrancoisDeBellescize** [comment]
Hi !
Is there any update ?
I'm using expo SDK 35 so RN 0.59.8 and we still have this problem  using `transform: [{ translateY: contentTranslate }]` where `contentTranslate` is an `interpolate()` of `Animated.Value`

**Comment by carthagan** [comment]
Hi there,
The problem seems to be related to the animation range of the interpolate function. There seems to be some kind of "resonance" in the scroll animation for certain relative values.
In my case (I am using it to make a header parallax effect), a simple workaround I found was to change the input range : 
From
`inputRange: [0,(HEADER_EXPANDED_HEIGHT-HEADER_HALF_HEIGHT)],` to `inputRange: [0,(HEADER_EXPANDED_HEIGHT-HEADER_HALF_HEIGHT)*1.5],` 
I then put some bottom padding to the `Animated.Scrollview` component: `contentContainerStyle={{paddingBottom: 25}}`
It is not very clean but it did the trick for me.

**Comment by benevbright** [comment]
I ended up to look into RN android.

https://github.com/facebook/react-native/issues/15445#issuecomment-326680200

@janicduplessis
You pointed the place out where this bug started. Could you help us?

**Comment by benevbright** [comment]
@kelset @janicduplessis 

https://github.com/facebook/react-native/blob/0ef0d3167e291f31ce01ceb729df77cc679d2330/ReactAndroid/src/main/java/com/facebook/react/views/scroll/OnScrollDispatchHelper.java#L39

We need to compose the current `translateY` value here. 
Do you know how to get the android `ScrollView`'s `transitionY`? 

I tried using every member getter like `this.getTransitionY()` but couldn't get desired value.

**Comment by boaz-lachman** [comment]
any update regarding this issue. It persists on Android 0.60.6 when I use a collapsible header for a scrollview

**Comment by feruzm** [comment]
`"react-native": "0.61.5"`
issue still persist

**Comment by kelset** [comment]
has anyone had the chance to test with the RC0 of 0.62?

**Comment by benevbright** [comment]
@kelset Did we have some PR for this issue?

**Comment by kelset** [comment]
I don't know tbh, but between 0.61 and 0.62 there is a "delta" of commits of 1200, so there is a small chance that there is a fix. I haven't been paying close attention so I can't tell for sure. Maybe what you could check is (via github) the history for the folder that has the logic for the translation and see if any commit seems to be referring to it.

**Comment by benevbright** [comment]
@kelset Ok, thanks for your response.

**Comment by benevbright** [comment]
@kelset 
on `0.62.0-rc.0`
still persists.

![Jan-07-2020 22-02-50](https://user-images.githubusercontent.com/916690/71929429-e4680100-3199-11ea-9f72-ce78e07eb053.gif)

**Comment by panda0603** [comment]
any updates on this?

**Comment by luco** [comment]
Could this be related to #27049?

**Comment by HarshitMadhav** [comment]
@luco I dont think so as because this issue is active on android only in iOS it is working fine. The demo that you provided might be an another issue.

**Comment by jesobreira** [comment]
Any advance on this?

**Comment by rita-chi** [comment]
> @benevbright Hello, I started using your react-navigation-collapsible unfortunately the bug on android where the header started to jump when scrolling slowly made it not suitable for production release. I made a hack way to avoid the "jumping bug" but i dont how to implement it on your library but i hope it helps
> 
> https://snack.expo.io/r1hwBv0wV - Here's the one with "Jumping Bug"
> https://snack.expo.io/Hk34BPCDN - Here's the one without the bug
> 
> I just add the following style
> 
> ```
> position: 'absolute',
> zIndex: 999,
> top: 0
> ```
> 
> i dont know but i think the `position: 'absolute'` removes the bug


I thought it was nonsense, but it helped me! Animation became smooth on Android. Thank you!

**Comment by esdotzed** [comment]
> @benevbright, I'm implementing an application to document a component library I own.
> 
> In the app, the header is animated and I went through the same problem described here.
> 
> To solve the problem, I made the following adjustments to my component.
> 
> 1 . Additional content is passed through the page to NavigationHeader via props
> 2. NavigationHeader looks at content height and tells page about new size
> 3. The page, which has ScrollView (or SectionList and etc), renders an empty element with this height received (a padding at the top), so the page does not use "transform: [{translateY: translateY} animation ] "(which is the source of the problem)
> 4. On the page, another aesthetic adjustment was to remove the vertical scroll bars (showsVerticalScrollIndicator = {false}). In the future I intend to create a virtual scroll bar, just to allow the visual response to the user about the screen position, discounting the height of the empty component.
> 
> The implementation files (and most important lines) are:
> 
> * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/NavigationHeader.tsx#L264-L288
> * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/NavigationHeader.tsx#L232-L235
> * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/GradientHeader.tsx#L29-L54
> * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/GradientHeader.tsx#L69-L70
> 
> Below are two videos with the result, (you can also run the application https://github.com/nidorx/rn-components-ui/tree/master/example and see the result [still under development] for yourself)
> 
> AnimationHeader - https://youtu.be/IyThm01At1g
> 
> Page padding top - https://youtu.be/kNwCq6xYEHQ
> 
> ![ezgif com-optimize](https://user-images.githubusercontent.com/675430/63904107-3a57bb80-c9e6-11e9-8c5f-453141560b7a.gif)

This seems to be a reasonable solution. However, when it comes to pull to refresh, the pull to refresh indicator (little circle) won't surface because there is an empty block on the top. I haven't figure out a good way to handle that...

**Comment by esdotzed** [comment]
> > @benevbright, I'm implementing an application to document a component library I own.
> > In the app, the header is animated and I went through the same problem described here.
> > To solve the problem, I made the following adjustments to my component.
> > 1 . Additional content is passed through the page to NavigationHeader via props
> > 2. NavigationHeader looks at content height and tells page about new size
> > 3. The page, which has ScrollView (or SectionList and etc), renders an empty element with this height received (a padding at the top), so the page does not use "transform: [{translateY: translateY} animation ] "(which is the source of the problem)
> > 4. On the page, another aesthetic adjustment was to remove the vertical scroll bars (showsVerticalScrollIndicator = {false}). In the future I intend to create a virtual scroll bar, just to allow the visual response to the user about the screen position, discounting the height of the empty component.
> > The implementation files (and most important lines) are:
> > 
> > * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/NavigationHeader.tsx#L264-L288
> > * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/NavigationHeader.tsx#L232-L235
> > * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/GradientHeader.tsx#L29-L54
> > * https://github.com/nidorx/rn-components-ui/blob/master/example/src/components/GradientHeader.tsx#L69-L70
> > 
> > Below are two videos with the result, (you can also run the application https://github.com/nidorx/rn-components-ui/tree/master/example and see the result [still under development] for yourself)
> > AnimationHeader - https://youtu.be/IyThm01At1g
> > Page padding top - https://youtu.be/kNwCq6xYEHQ
> > ![ezgif com-optimize](https://user-images.githubusercontent.com/675430/63904107-3a57bb80-c9e6-11e9-8c5f-453141560b7a.gif)
> 
> This seems to be a reasonable solution. However, when it comes to pull to refresh, the pull to refresh indicator (little circle) won't surface because there is an empty block on the top. I haven't figure out a good way to handle that...

Actually I solved the problem by applying contentInset and contentOffset for IOS and progressViewOffset for android. Note that for Android I added an additional on the top of the list as a place holder while for iOS, it is not needed. And everything works perfectly for me now.

**Comment by KingAmo** [comment]
@esdotzed could you please show a demo ? thx

**Comment by vikasg603** [comment]
@react-native-bot @shergin @hramos @sahrens this issue is not fixed till now, Please if possible will you guys look into this issue.
it's almost 2 years gone but still, this issue is open.

**Comment by vikasg603** [comment]
> @react-native-bot @shergin @hramos @sahrens this issue is not fixed till now, Please if possible will you guys look into this issue.
> it's almost 2 years gone but still, this issue is open.

Those who are looking for a solution to this issue, Just make your input range 2 times of that output range
like this
            inputRange: [0, 2*HEADER_EXPANDED_HEIGHT],
            outputRange: [0, -HEADER_EXPANDED_HEIGHT]

**Comment by thiago-sandes** [comment]
> > @react-native-bot @shergin @hramos @sahrens this issue is not fixed till now, Please if possible will you guys look into this issue.
> > it's almost 2 years gone but still, this issue is open.
> 
> Those who are looking for a solution to this issue, Just make your input range 2 times of that output range
> like this
> inputRange: [0, 2*HEADER_EXPANDED_HEIGHT],
> outputRange: [0, -HEADER_EXPANDED_HEIGHT]

This works well on Android! Thanks :)

**Comment by darcoola** [comment]
Same problem here. Multiplying input range by 2 is interesting, but it changes the behaviour of animation (slowing down animation). Is there a chance that there will be a fix to this problem?

**Comment by vikasg603** [comment]
> Same problem here. Multiplying the input range by 2 is interesting, but it changes the behavior of animation (slowing down animation). Is there a chance that there will be a fix to this problem?

I don't exactly know how multiplying input range 2 times solving this issue but what you can do is that in final animation output you can multiply some value to get the desired result.

Example like if you want same input range and output range, you can use animation multiplication to multiply your final animation value with 2 and get desired value.

**Comment by thiago-sandes** [comment]
> Same problem here. Multiplying input range by 2 is interesting, but it changes the behaviour of animation (slowing down animation). Is there a chance that there will be a fix to this problem?

Yes, @vikasg603 is right. 
You have to play with the numbers until you reach the expected result! This has a little math :)

**Comment by darcoola** [comment]
The problem is, that I want the same behavior on Android and iOS. On iOS it works perfectly, on Android not. When I multiply input by 2 it works better (but still there is flickering). It works even better when I multiply input by 4... 

  ```
const scrollY = useRef(new Animated.Value(0)).current;

  const headerTranslateY = scrollY.interpolate({
    inputRange: [0, 2 * HEADER_SCROLL_DISTANCE],
    outputRange: [0, -HEADER_SCROLL_DISTANCE],
    extrapolate: 'clamp',
  });
```

What I mean, is by doing that (with hiding header) i do slow down the animation, meaning the header is hiding slower. When I multiply my output to make it faster I'm back in the point where there is a lot of flickering - screen is jumping.

```
  const scrollY = useRef(new Animated.Value(0)).current;

  const headerTranslateY = scrollY.interpolate({
    inputRange: [0, 2 * HEADER_SCROLL_DISTANCE],
    outputRange: [0, -2 * HEADER_SCROLL_DISTANCE],
    extrapolate: 'clamp',
  });
```

**Comment by darcoola** [comment]
> Finally for your desired result multiply your headerTranslateY with some desired number so your final answer will be something like
> 
> const scrollY = useRef(new Animated.Value(0)).current;
> 
> const headerTranslateY = scrollY.interpolate({
> inputRange: [0, 2 * HEADER_SCROLL_DISTANCE],
> outputRange: [0, -2 * HEADER_SCROLL_DISTANCE],
> extrapolate: 'clamp',
> })
> 
> const headerTranslateYNew = Animated.multiply(headerTranslateY, 2); //Check this multiply by 2
> 
> **Note** : I am not sure about this, You have to try this by yourself.

Unfortunately the result is the same as before - jumping screen... But thanks for your answers @vikasg603

**Comment by darcoola** [comment]
iOS
![ios](https://user-images.githubusercontent.com/46839220/88951958-fe347700-d296-11ea-9e5e-e63c3b830364.gif)

Android
![android](https://user-images.githubusercontent.com/46839220/88951982-0be9fc80-d297-11ea-8802-0a0b3cd48be3.gif)

**Comment by vikasg603** [comment]
> iOS
> ![ios](https://user-images.githubusercontent.com/46839220/88951958-fe347700-d296-11ea-9e5e-e63c3b830364.gif)
> 
> Android
> ![android](https://user-images.githubusercontent.com/46839220/88951982-0be9fc80-d297-11ea-8802-0a0b3cd48be3.gif)

iOS was never a problem, but it was android which was causing the issue,
I also don't have any other suggestion If it's not working :(

**Comment by vinhtran6921** [comment]
I still stuck on android. Anyone have solutions for this ?

**Comment by anhquan291** [comment]
Same issue here... hic hic. Hope they will fix it soon

**Comment by huyhai** [comment]
any update pls

**Comment by soufian97** [comment]
The issue still exists on rn 0.63

**Comment by namchuai** [comment]
Dissapointed. The issue still open for more than two years...

I think this framework is dead.

**Comment by huyhai** [comment]
> Dissapointed. The issue still open for more than two years...
> 
> I think this framework is dead.

try this:
   const headerHeight = isIos() ? HeaderHeight : HeaderHeight * 2;

**Comment by samuelvisscher** [comment]
For me also HeaderHeight * 1.2 helped, which put it in the range of the acceptable

**Comment by dayze** [comment]
Still happening in RN 0.63 😬

**Comment by matanrokach** [comment]
Any workaround for this issue?
Does anyone have a working example to share?

**Comment by borasumer** [comment]
I can't believe such a fundamental mobile app feature can't be handled due to a bug that's been around for ages. It 2021, this thing is still unsolved. I am wowed.

**Comment by AND-GORNIY** [comment]
It can be a little tricky but try to avoid set translate prop to FlatList`s style, or component that wrap Flatlist, jumps will disappear. For adding empty space before first item you can set contentContainer={{paddingTop:}}. It was in my case, hope this help someone.

**Comment by arioki1** [comment]
> It can be a little tricky but try to avoid set translate prop to FlatList`s style, or component that wrap Flatlist, jumps will disappear. For adding empty space before first item you can set contentContainer={{paddingTop:}}. It was in my case, hope this help someone.

whether you can give an example of his code

**Comment by archcorsair** [comment]
Has anyone tested this one RN 0.64?

**Comment by arnsa** [comment]
> Has anyone tested this on RN 0.64?

Yup, still the same :(((((

**Comment by ChiragMDave** [comment]
The problem isn't in android but lies somewhere in your code which deals with the height values. You can, smoothly transform, translateY number of Animated.Views simultanously e.g. Header view, middle view, bottom view using Pan, ScrollView or Flatlist. 
Note: You cannot animate using height property while using useNativeDriver: true, it should be false. 
1. Interpolation negative outputRange value should be less than equllTo inputRange value e.g. iR:[0, 200], oR:[0, -199]. Always greater than -201 and less than 200.
2. Adjust paddingBottom in contentContainerStyle. You need to make it sure virtually that you have same invisible height as the visible scrolling area.
3. useNativeDriver: true

**Comment by mehthabux** [comment]
any luck ?

**Comment by Nagato717** [comment]
> > Dissapointed. The issue still open for more than two years...
> > I think this framework is dead.
> 
> try this:
> const headerHeight = isIos() ? HeaderHeight : HeaderHeight * 2;

try this workaround, you can even *4 for smoother

**Comment by jorisvo2** [comment]
> The problem isn't in android but lies somewhere in your code which deals with the height values. You can, smoothly transform, translateY number of Animated.Views simultanously e.g. Header view, middle view, bottom view using Pan, ScrollView or Flatlist.
> Note: You cannot animate using height property while using useNativeDriver: true, it should be false.
> 
> 1. Interpolation negative outputRange value should be less than equllTo inputRange value e.g. iR:[0, 200], oR:[0, -199]. Always greater than -201 and less than 200.
> 2. Adjust paddingBottom in contentContainerStyle. You need to make it sure virtually that you have same invisible height as the  sum of visible animating items area.
> 3. useNativeDriver: true

I've these value and isn't smooth ...

```
    const flatListTop = scrollY.interpolate({
        inputRange: [0, 200],
        outputRange: [0, -190],
        extrapolate: 'clamp',
    });
```

Any idea?

**Comment by archcorsair** [comment]
I can confirm this issue still persists on `0.64.2`.
It's a real bummer because we can't implement our chosen designs on Android meanwhile they work perfectly well on iOS. 😢 Hoping this issue gets the attention it deserves, as animations are quickly becoming a standard in react native dev's toolkits. I'm still seeking a useful workaround, I will share if/when that comes around!

**Comment by nica0012** [comment]
0.65, still an problem :(

**Comment by ngodangkhoa** [comment]
anyone fixed?

**Comment by droplessjake** [comment]
Having a similar problem currently with an Animated.View that uses translateY.
It jumps about when the page reloads or anything causes it to update.

https://user-images.githubusercontent.com/83917938/140329992-0416d629-a2e6-43dc-b3c3-6175ccae0a9e.mp4

**Comment by chareefdev** [comment]
0.66.3 same

**Comment by ddikodroid** [comment]
> Are there any PRs open to try and fix this? Or commits already on master?

nope

**Comment by Deodes** [comment]
I was trying to implement collapsible header and meet this dumb problem on Android. No matter what I use to animate ScrollView (paddingTop, translateY, height). This is quite serious bug and it exists for a really long time, I don't believe that using react-native I cannot implement such an easy animation on Android...

It has redproduced since 2017: https://github.com/facebook/react-native/issues/15445

If there aren't any blocks, contributors please pay attention to this problem

**Comment by KingAmo** [comment]
@Deodes maybe you could try   [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) instead of `Animated` ?

**Comment by Deodes** [comment]
@KingAmo I updated my comment

**Comment by bekatd** [comment]
Why this silly bug exists for a such really long time?

**Comment by yogendrajs** [comment]
still a bug!!!

**Comment by MillerMatias** [comment]
Any updates on this? Just ran into this problem on react-native 0.69.5.

**Comment by poojan010** [comment]
can not make animatable header with Tab View
due to this bug

**Comment by Mohamedghaly140** [comment]
we are in 2023 and still a bug, the UI gets vibrated while scrolling on the Android platform RN 0.71.4
when this bug may be resolved !!

**Comment by Mohamedghaly140** [comment]
we are in 2023 and still a bug, the UI gets vibrated while scrolling on the Android platform RN 0.71.4
when this bug may be resolved !!
i hope to be resolved as soon as possible, it's critical one

**Comment by baesumin** [comment]
+1

**Comment by MDG-MMeksasi** [comment]
It's really weird that this bug still exist till the day, I'm not a senior but I managed to overcome it like that so I noticed that the scrollview was bouncing by the height of the translateY, so you can use these conditions on android also you will need the **marginBottom** on the view of the list to hide the white part on the bottom when translating hope this will help.

```javascript
  const scrollY = useSharedValue(0);
  const headerHeight = 90; // Height of the header
  const progress = useSharedValue(0);
  const translateTheshold = 50; // Threshold to start the animation
  const scrollHandler = useAnimatedScrollHandler(event => {
    const offsetY = event.contentOffset.y;

    // scroll down
    if (offsetY > scrollY.value && progress.value === 0) {
      if (offsetY > translateTheshold) {
        progress.value = withTiming(1, {
          duration: 500,
        });
        // subtract header height to scrollY value to fix android bounce issue
        scrollY.value =
          scrollY.value - headerHeight < 0 ? 0 : scrollY.value - headerHeight;
      }
      // scroll up
    } else if (offsetY < scrollY.value && progress.value === 1) {
      // add header height to scrollY value to fix android bounce issue
      scrollY.value = scrollY.value + headerHeight;
      progress.value = withTiming(0, {
        duration: 500,
      });
    }

    scrollY.value = withTiming(offsetY);
  });

  const translateYStyle = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateY: interpolate(
            progress.value,
            [0, 1],
            [0, -headerHeight],
            Extrapolate.CLAMP,
          ),
        },
      ],
    };
  });

 <ScreenContent style={styles.ph0}>
      <HorizontalPaddingView>
        <Animated.View
          style={[
            {
              backgroundColor: 'red',
              height: 90,
              alignItems: 'center',
              justifyContent: 'center',
            },
            translateYStyle,
          ]}>
          <Text preset="header">{t('claim.summary.heading')}</Text>
      </HorizontalPaddingView>

      <Animated.View
        style={[{flex: 1, marginBottom: -headerHeight}, translateYStyle]}>
        <AnimatedFlashList
          showsVerticalScrollIndicator={false}
          bounces={false}
          scrollEventThrottle={16}
          onScroll={scrollHandler}
          data={claim.attributes.groups}
          renderItem={renderItem}
          estimatedItemSize={350}
        />
      </Animated.View>
  </ScreenContent>
```

**Comment by caiopngoncalves** [comment]
@MDG-MMeksasi could you explain how your solution works? I'm having a hard time trying to understand

**Comment by jvfalco1** [comment]
I'm facing this same issue on RN 0.71.5

**Comment by MDG-MMeksasi** [comment]
@jvfalco1 @caiopngoncalves did you try my solution? could you try it please

**Comment by caiopngoncalves** [comment]
@MDG-MMeksasi Yeah, It works. I just wanted to understand more about the problem

**Comment by jvfalco1** [comment]
> @jvfalco1 @caiopngoncalves did you try my solution? could you try it please just to see if it works properly

Actually dont, because Im facing the same issue but Im not translating it, Im reducing the Height of the component.

**Comment by MDG-MMeksasi** [comment]
> 

it should be better if you target translateY, otherwise it should always be laggy on android

**Comment by jvfalco1** [comment]
@MDG-MMeksasi Even with translation I get the same error, Unfortunately I have to use the height. Unfortunately I think ill not be able to fix this

**Comment by H4mxa** [comment]
+1

**Comment by yosukapro** [comment]
Any answer for this? It since 5 years and still don't see the solution

**Comment by iamolegga** [comment]
.

**Comment by EF09FE** [comment]
any updates?

**Comment by archcorsair** [comment]
Bump

**Comment by aminhdev** [comment]
.
